# Generated by Django 4.2.5 on 2023-09-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0013_alter_rides_adv_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='b1_color',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='b2_color',
        ),
    ]
